services:
  app-migrate:
    image: myapp:latest
    build:
      context: .
    command: ["migrate"]
    depends_on:
      db:
        condition: service_healthy

  app-service:
    image: myapp:latest
    build:
      context: .
    ports:
      - "8000:8000"
    command: ["runserver", "0.0.0.8000"]
    depends_on:
      app-migrate:
        condition: service_completed_successfully

  db:
    image: postgres:18
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    healthcheck:
      test: pg_isready -U myuser -d db_prod
      interval: 10s
      timeout: 3s
      retries: 3
