# Generated by Django 5.2.7 on 2025-11-07 07:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_blog_created_at_blog_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes",
            name="content",
            field=models.TextField(
                default=django.utils.timezone.now, verbose_name="Content of the note"
            ),
            preserve_default=False,
        ),
    ]
