# Generated by Django 5.2.7 on 2025-11-20 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_textblock"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notes",
            options={"verbose_name": "Note", "verbose_name_plural": "Notes"},
        ),
        migrations.AlterField(
            model_name="textblock",
            name="note",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="notes.notes",
            ),
        ),
    ]
