# Generated by Django 5.2.7 on 2025-11-21 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0005_alter_notes_options_alter_textblock_note"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TextBlock",
        ),
    ]
